package com.jrsii.main.frontend.user;

import java.util.List;

import com.jrsii.entities.Adressen;
import com.jrsii.entities.Adressgruppen;
import com.jrsii.entities.Adressgruppenverweise;
import com.jrsii.entities.StudentQueries;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.HorizontalSplitPanel;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.RichTextArea;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

import java.io.*;

public class UserSchueler extends CustomComponent implements View {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_Main;
	@AutoGenerated
	private HorizontalSplitPanel horizontalSplitPanel_Main;
	@AutoGenerated
	private VerticalLayout verticalLayout_Right;
	@AutoGenerated
	private Panel panel_Right;
	@AutoGenerated
	private VerticalLayout verticalLayout_PanelRight;
	@AutoGenerated
	private GridLayout gridLayout_RightPanel;
	@AutoGenerated
	private Button button_NeueAdresseEingeben;
	@AutoGenerated
	private Button button_suchen;
	@AutoGenerated
	private GridLayout gridLayout_StudentInfo;
	@AutoGenerated
	private TextField textField_Email;
	@AutoGenerated
	private Label label_Email;
	@AutoGenerated
	private TextField textField_Telefone;
	@AutoGenerated
	private Label label_Telefon;
	@AutoGenerated
	private TextField textField_Ort;
	@AutoGenerated
	private Label label_Ort;
	@AutoGenerated
	private TextField textField_PLZ;
	@AutoGenerated
	private Label label_PLZ;
	@AutoGenerated
	private TextField textField_Adressgruppe;
	@AutoGenerated
	private Label label_Adressgruppe;
	@AutoGenerated
	private TextField textField_Instrument;
	@AutoGenerated
	private Label label_Instrument;
	@AutoGenerated
	private TextField textField_Nachname;
	@AutoGenerated
	private Label label_Nachname;
	@AutoGenerated
	private TextField textField_Vornam;
	@AutoGenerated
	private Label label_Vorname;
	@AutoGenerated
	private VerticalLayout verticalLayout_Left;
	@AutoGenerated
	private Button button_Abmelden;
	@AutoGenerated
	private Button button_BenutzerOptionen;
	@AutoGenerated
	private Button button_SetUp;
	@AutoGenerated
	private Button button_Marketing;
	@AutoGenerated
	private Button button_Kurse;
	@AutoGenerated
	private Button button_Lehrer;
	@AutoGenerated
	private Button button_SchuelerStudent;
	public Adressen adressen;
	public static final String USER_SCHUELER_PAGE = "UserSchuelerPage";
	/**
	 * 
	 */
	private static final long serialVersionUID = 521985652200676883L;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public UserSchueler() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		horizontalSplitPanel_Main.setSplitPosition(13);
		
//		EntityManager em = JPAContainerFactory.createEntityManagerForPersistenceUnit(Login.PERSISTANCE_UNIT);
//		Query q = em.createQuery("from Anschriften WHERE b.vorname LIKE %?% OR b.nachname LIKE %?% ");
		// FROM Benutzer b WHERE b.benutzername = ?1 AND  b.kennwort = ?2 "
		String adressgruppeName = textField_Adressgruppe.getValue();
		
		StudentQueries studentQueries = new StudentQueries();
		final List<Adressen> adressenListe = studentQueries.findAdressenFromAdressgruppenJOINAdressgruppenverweiseWHEREAdressgruppenNAMEis(adressgruppeName);
		Table tableResults = new Table();
		tableResults.setSizeFull();
		tableResults.setSelectable(true);
		tableResults.setImmediate(true);
//		tableResults.setContainerDataSource(tableResults, adressenGruppenListe);
		
		
        button_suchen.addClickListener(new Button.ClickListener() {
			
			@Override
			public void buttonClick(com.vaadin.ui.Button.ClickEvent event) {
				File file = new File("C:/Users/mayz/Desktop/text.txt");
				if(!file.exists()){
						try {
							file.createNewFile();
						} catch (IOException e) {
							e.printStackTrace();
						}
				}
				FileWriter fw = null;
				try {
					fw = new FileWriter(file.getAbsoluteFile());
				} catch (IOException e) {
					e.printStackTrace();
				}

				BufferedWriter bw= new BufferedWriter(fw);
				for(Adressen adressen : adressenListe ){
					Integer adressenID = adressen.getId();
					try {
						bw.write(adressenID.toString());
						bw.newLine();
					} catch (IOException e) {
						e.printStackTrace();
					}

				}
				try {
					bw.close();
				} catch (IOException e) {
					e.printStackTrace();
				}
				
			}
		});
		
		// TODO add user code here
	}

	@Override
	public void enter(ViewChangeEvent event) {
		panel_Right.setCaption("Schüler/Student");
		
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// horizontalLayout_Main
		horizontalLayout_Main = buildHorizontalLayout_Main();
		mainLayout.addComponent(horizontalLayout_Main,
				"top:0.0px;right:-2.0px;bottom:2.0px;left:0.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_Main() {
		// common part: create layout
		horizontalLayout_Main = new HorizontalLayout();
		horizontalLayout_Main.setImmediate(false);
		horizontalLayout_Main.setWidth("100.0%");
		horizontalLayout_Main.setHeight("100.0%");
		horizontalLayout_Main.setMargin(false);
		
		// horizontalSplitPanel_Main
		horizontalSplitPanel_Main = buildHorizontalSplitPanel_Main();
		horizontalLayout_Main.addComponent(horizontalSplitPanel_Main);
		
		return horizontalLayout_Main;
	}

	@AutoGenerated
	private HorizontalSplitPanel buildHorizontalSplitPanel_Main() {
		// common part: create layout
		horizontalSplitPanel_Main = new HorizontalSplitPanel();
		horizontalSplitPanel_Main.setImmediate(false);
		horizontalSplitPanel_Main.setWidth("100.0%");
		horizontalSplitPanel_Main.setHeight("100.0%");
		
		// verticalLayout_Left
		verticalLayout_Left = buildVerticalLayout_Left();
		horizontalSplitPanel_Main.addComponent(verticalLayout_Left);
		
		// verticalLayout_Right
		verticalLayout_Right = buildVerticalLayout_Right();
		horizontalSplitPanel_Main.addComponent(verticalLayout_Right);
		
		return horizontalSplitPanel_Main;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_Left() {
		// common part: create layout
		verticalLayout_Left = new VerticalLayout();
		verticalLayout_Left.setImmediate(false);
		verticalLayout_Left.setWidth("100.0%");
		verticalLayout_Left.setHeight("100.0%");
		verticalLayout_Left.setMargin(false);
		
		// button_SchuelerStudent
		button_SchuelerStudent = new Button();
		button_SchuelerStudent.setCaption("schüler/student");
		button_SchuelerStudent.setImmediate(true);
		button_SchuelerStudent.setWidth("-1px");
		button_SchuelerStudent.setHeight("-1px");
		verticalLayout_Left.addComponent(button_SchuelerStudent);
		verticalLayout_Left.setComponentAlignment(button_SchuelerStudent,
				new Alignment(34));
		
		// button_Lehrer
		button_Lehrer = new Button();
		button_Lehrer.setCaption("lehrer");
		button_Lehrer.setImmediate(true);
		button_Lehrer.setWidth("-1px");
		button_Lehrer.setHeight("-1px");
		verticalLayout_Left.addComponent(button_Lehrer);
		verticalLayout_Left.setComponentAlignment(button_Lehrer, new Alignment(
				34));
		
		// button_Kurse
		button_Kurse = new Button();
		button_Kurse.setCaption("kurse");
		button_Kurse.setImmediate(true);
		button_Kurse.setWidth("-1px");
		button_Kurse.setHeight("-1px");
		verticalLayout_Left.addComponent(button_Kurse);
		verticalLayout_Left.setComponentAlignment(button_Kurse, new Alignment(
				34));
		
		// button_Marketing
		button_Marketing = new Button();
		button_Marketing.setCaption("marketing");
		button_Marketing.setImmediate(true);
		button_Marketing.setWidth("-1px");
		button_Marketing.setHeight("-1px");
		verticalLayout_Left.addComponent(button_Marketing);
		verticalLayout_Left.setComponentAlignment(button_Marketing,
				new Alignment(34));
		
		// button_SetUp
		button_SetUp = new Button();
		button_SetUp.setCaption("set up");
		button_SetUp.setImmediate(true);
		button_SetUp.setWidth("-1px");
		button_SetUp.setHeight("-1px");
		verticalLayout_Left.addComponent(button_SetUp);
		verticalLayout_Left.setComponentAlignment(button_SetUp, new Alignment(
				34));
		
		// button_BenutzerOptionen
		button_BenutzerOptionen = new Button();
		button_BenutzerOptionen.setCaption("benutzer optionen");
		button_BenutzerOptionen.setImmediate(true);
		button_BenutzerOptionen.setWidth("-1px");
		button_BenutzerOptionen.setHeight("-1px");
		verticalLayout_Left.addComponent(button_BenutzerOptionen);
		verticalLayout_Left.setComponentAlignment(button_BenutzerOptionen,
				new Alignment(34));
		
		// button_Abmelden
		button_Abmelden = new Button();
		button_Abmelden.setCaption("abmelden");
		button_Abmelden.setImmediate(true);
		button_Abmelden.setWidth("-1px");
		button_Abmelden.setHeight("-1px");
		verticalLayout_Left.addComponent(button_Abmelden);
		verticalLayout_Left.setComponentAlignment(button_Abmelden,
				new Alignment(10));
		
		return verticalLayout_Left;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_Right() {
		// common part: create layout
		verticalLayout_Right = new VerticalLayout();
		verticalLayout_Right.setImmediate(false);
		verticalLayout_Right.setWidth("100.0%");
		verticalLayout_Right.setHeight("100.0%");
		verticalLayout_Right.setMargin(false);
		
		// panel_Right
		panel_Right = buildPanel_Right();
		verticalLayout_Right.addComponent(panel_Right);
		verticalLayout_Right.setExpandRatio(panel_Right, 1.0f);
		verticalLayout_Right.setComponentAlignment(panel_Right, new Alignment(
				48));
		
		return verticalLayout_Right;
	}

	@AutoGenerated
	private Panel buildPanel_Right() {
		// common part: create layout
		panel_Right = new Panel();
		panel_Right.setImmediate(false);
		panel_Right.setWidth("100.0%");
		panel_Right.setHeight("100.0%");
		
		// verticalLayout_PanelRight
		verticalLayout_PanelRight = buildVerticalLayout_PanelRight();
		panel_Right.setContent(verticalLayout_PanelRight);
		
		return panel_Right;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_PanelRight() {
		// common part: create layout
		verticalLayout_PanelRight = new VerticalLayout();
		verticalLayout_PanelRight.setImmediate(false);
		verticalLayout_PanelRight.setWidth("115.78%");
		verticalLayout_PanelRight.setHeight("100.0%");
		verticalLayout_PanelRight.setMargin(false);
		
		// gridLayout_RightPanel
		gridLayout_RightPanel = buildGridLayout_RightPanel();
		verticalLayout_PanelRight.addComponent(gridLayout_RightPanel);
		verticalLayout_PanelRight.setComponentAlignment(gridLayout_RightPanel,
				new Alignment(48));
		
		return verticalLayout_PanelRight;
	}

	@AutoGenerated
	private GridLayout buildGridLayout_RightPanel() {
		// common part: create layout
		gridLayout_RightPanel = new GridLayout();
		gridLayout_RightPanel.setImmediate(false);
		gridLayout_RightPanel.setWidth("100.0%");
		gridLayout_RightPanel.setHeight("100.0%");
		gridLayout_RightPanel.setMargin(false);
		gridLayout_RightPanel.setColumns(2);
		gridLayout_RightPanel.setRows(2);
		
		// gridLayout_StudentInfo
		gridLayout_StudentInfo = buildGridLayout_StudentInfo();
		gridLayout_RightPanel.addComponent(gridLayout_StudentInfo, 0, 0);
		gridLayout_RightPanel.setComponentAlignment(gridLayout_StudentInfo,
				new Alignment(33));
		
		// button_suchen
		button_suchen = new Button();
		button_suchen.setCaption("suchen");
		button_suchen.setImmediate(true);
		button_suchen.setWidth("-1px");
		button_suchen.setHeight("-1px");
		gridLayout_RightPanel.addComponent(button_suchen, 0, 1);
		gridLayout_RightPanel.setComponentAlignment(button_suchen,
				new Alignment(48));
		
		// button_NeueAdresseEingeben
		button_NeueAdresseEingeben = new Button();
		button_NeueAdresseEingeben.setCaption("neue adresse eingeben");
		button_NeueAdresseEingeben.setImmediate(true);
		button_NeueAdresseEingeben.setWidth("-1px");
		button_NeueAdresseEingeben.setHeight("-1px");
		gridLayout_RightPanel.addComponent(button_NeueAdresseEingeben, 1, 1);
		gridLayout_RightPanel.setComponentAlignment(button_NeueAdresseEingeben,
				new Alignment(48));
		
		return gridLayout_RightPanel;
	}

	@AutoGenerated
	private GridLayout buildGridLayout_StudentInfo() {
		// common part: create layout
		gridLayout_StudentInfo = new GridLayout();
		gridLayout_StudentInfo.setImmediate(false);
		gridLayout_StudentInfo.setWidth("100.0%");
		gridLayout_StudentInfo.setHeight("100.0%");
		gridLayout_StudentInfo.setMargin(false);
		gridLayout_StudentInfo.setColumns(2);
		gridLayout_StudentInfo.setRows(8);
		
		// label_Vorname
		label_Vorname = new Label();
		label_Vorname.setImmediate(false);
		label_Vorname.setWidth("-1px");
		label_Vorname.setHeight("-1px");
		label_Vorname.setValue("vorname");
		gridLayout_StudentInfo.addComponent(label_Vorname, 0, 0);
		gridLayout_StudentInfo.setComponentAlignment(label_Vorname,
				new Alignment(48));
		
		// textField_Vornam
		textField_Vornam = new TextField();
		textField_Vornam.setImmediate(false);
		textField_Vornam.setWidth("-1px");
		textField_Vornam.setHeight("-1px");
		gridLayout_StudentInfo.addComponent(textField_Vornam, 1, 0);
		gridLayout_StudentInfo.setComponentAlignment(textField_Vornam,
				new Alignment(48));
		
		// label_Nachname
		label_Nachname = new Label();
		label_Nachname.setImmediate(false);
		label_Nachname.setWidth("-1px");
		label_Nachname.setHeight("-1px");
		label_Nachname.setValue("nachname");
		gridLayout_StudentInfo.addComponent(label_Nachname, 0, 1);
		gridLayout_StudentInfo.setComponentAlignment(label_Nachname,
				new Alignment(48));
		
		// textField_Nachname
		textField_Nachname = new TextField();
		textField_Nachname.setImmediate(false);
		textField_Nachname.setWidth("-1px");
		textField_Nachname.setHeight("-1px");
		gridLayout_StudentInfo.addComponent(textField_Nachname, 1, 1);
		gridLayout_StudentInfo.setComponentAlignment(textField_Nachname,
				new Alignment(48));
		
		// label_Instrument
		label_Instrument = new Label();
		label_Instrument.setImmediate(false);
		label_Instrument.setWidth("-1px");
		label_Instrument.setHeight("-1px");
		label_Instrument.setValue("instrument");
		gridLayout_StudentInfo.addComponent(label_Instrument, 0, 2);
		gridLayout_StudentInfo.setComponentAlignment(label_Instrument,
				new Alignment(48));
		
		// textField_Instrument
		textField_Instrument = new TextField();
		textField_Instrument.setImmediate(false);
		textField_Instrument.setWidth("-1px");
		textField_Instrument.setHeight("-1px");
		gridLayout_StudentInfo.addComponent(textField_Instrument, 1, 2);
		gridLayout_StudentInfo.setComponentAlignment(textField_Instrument,
				new Alignment(48));
		
		// label_Adressgruppe
		label_Adressgruppe = new Label();
		label_Adressgruppe.setImmediate(false);
		label_Adressgruppe.setWidth("-1px");
		label_Adressgruppe.setHeight("-1px");
		label_Adressgruppe.setValue("adressgruppe");
		gridLayout_StudentInfo.addComponent(label_Adressgruppe, 0, 3);
		gridLayout_StudentInfo.setComponentAlignment(label_Adressgruppe,
				new Alignment(48));
		
		// textField_Adressgruppe
		textField_Adressgruppe = new TextField();
		textField_Adressgruppe.setImmediate(false);
		textField_Adressgruppe.setWidth("-1px");
		textField_Adressgruppe.setHeight("-1px");
		gridLayout_StudentInfo.addComponent(textField_Adressgruppe, 1, 3);
		gridLayout_StudentInfo.setComponentAlignment(textField_Adressgruppe,
				new Alignment(48));
		
		// label_PLZ
		label_PLZ = new Label();
		label_PLZ.setImmediate(false);
		label_PLZ.setWidth("-1px");
		label_PLZ.setHeight("-1px");
		label_PLZ.setValue("PLZ");
		gridLayout_StudentInfo.addComponent(label_PLZ, 0, 4);
		gridLayout_StudentInfo.setComponentAlignment(label_PLZ, new Alignment(
				48));
		
		// textField_PLZ
		textField_PLZ = new TextField();
		textField_PLZ.setImmediate(false);
		textField_PLZ.setWidth("-1px");
		textField_PLZ.setHeight("-1px");
		gridLayout_StudentInfo.addComponent(textField_PLZ, 1, 4);
		gridLayout_StudentInfo.setComponentAlignment(textField_PLZ,
				new Alignment(48));
		
		// label_Ort
		label_Ort = new Label();
		label_Ort.setImmediate(false);
		label_Ort.setWidth("-1px");
		label_Ort.setHeight("-1px");
		label_Ort.setValue("Ort");
		gridLayout_StudentInfo.addComponent(label_Ort, 0, 5);
		gridLayout_StudentInfo.setComponentAlignment(label_Ort, new Alignment(
				48));
		
		// textField_Ort
		textField_Ort = new TextField();
		textField_Ort.setImmediate(false);
		textField_Ort.setWidth("-1px");
		textField_Ort.setHeight("-1px");
		gridLayout_StudentInfo.addComponent(textField_Ort, 1, 5);
		gridLayout_StudentInfo.setComponentAlignment(textField_Ort,
				new Alignment(48));
		
		// label_Telefon
		label_Telefon = new Label();
		label_Telefon.setImmediate(false);
		label_Telefon.setWidth("-1px");
		label_Telefon.setHeight("-1px");
		label_Telefon.setValue("telefon");
		gridLayout_StudentInfo.addComponent(label_Telefon, 0, 6);
		gridLayout_StudentInfo.setComponentAlignment(label_Telefon,
				new Alignment(48));
		
		// textField_Telefone
		textField_Telefone = new TextField();
		textField_Telefone.setImmediate(false);
		textField_Telefone.setWidth("-1px");
		textField_Telefone.setHeight("-1px");
		gridLayout_StudentInfo.addComponent(textField_Telefone, 1, 6);
		gridLayout_StudentInfo.setComponentAlignment(textField_Telefone,
				new Alignment(48));
		
		// label_Email
		label_Email = new Label();
		label_Email.setImmediate(false);
		label_Email.setWidth("-1px");
		label_Email.setHeight("-1px");
		label_Email.setValue("Email");
		gridLayout_StudentInfo.addComponent(label_Email, 0, 7);
		gridLayout_StudentInfo.setComponentAlignment(label_Email,
				new Alignment(48));
		
		// textField_Email
		textField_Email = new TextField();
		textField_Email.setImmediate(false);
		textField_Email.setWidth("-1px");
		textField_Email.setHeight("-1px");
		gridLayout_StudentInfo.addComponent(textField_Email, 1, 7);
		gridLayout_StudentInfo.setComponentAlignment(textField_Email,
				new Alignment(48));
		
		return gridLayout_StudentInfo;
	}

}
