package com.jrsii.view.frontend;

import com.jrsii.data.DataAdminKennwortAendern;
import com.jrsii.data.DataLogin;
import com.jrsii.main.JrsiiUI;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.navigator.Navigator;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Notification;
import com.vaadin.ui.Panel;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

public class Admin_KennwortAendern extends CustomComponent implements View {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */


	@AutoGenerated
	private AbsoluteLayout mainLayout;

	@AutoGenerated
	private HorizontalLayout horizontalLayout_Main;

	@AutoGenerated
	private VerticalLayout verticalLayout_Right;

	@AutoGenerated
	private Panel panel_Content;

	@AutoGenerated
	private VerticalLayout verticalLayout_Panel;

	@AutoGenerated
	private Button button_Zusenden;

	@AutoGenerated
	private PasswordField passwordField_neseKennwortBestaetigenReslut;

	@AutoGenerated
	private Label label_neuesKennwortBestaetigen;

	@AutoGenerated
	private PasswordField passwordField_neuesKennwortResult;

	@AutoGenerated
	private Label label_neuesKennwortEingeben;

	@AutoGenerated
	private PasswordField passwordField_altesKennwortReslut;

	@AutoGenerated
	private Label label_altesKennwortEingeben;

	@AutoGenerated
	private TextField textField_adminBenutzernameResult;

	@AutoGenerated
	private Label label_AdminBenutzername;

	@AutoGenerated
	private VerticalLayout verticalLayout_Left;

	@AutoGenerated
	private Button button_abmelden;

	@AutoGenerated
	private Button button_administrator;

	public static final String ADMIN_KENNWORT_AENDERN = "adminKennwortAendern";
	public Navigator navigator;

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public Admin_KennwortAendern() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		textField_adminBenutzernameResult.setValue(DataLogin.dataBenutzername);
		try {
			button_Zusenden.addClickListener(new Button.ClickListener() {
				
				@Override
				public void buttonClick(ClickEvent event) {
					
					DataAdminKennwortAendern.adminNeuesKennwortData = passwordField_neuesKennwortResult.getValue();
					DataAdminKennwortAendern.adminNeuesKennwortBestaetigenData = passwordField_neseKennwortBestaetigenReslut.getValue();
					
					DataAdminKennwortAendern.adminAltesKennwortData = passwordField_altesKennwortReslut.getValue();
					DataAdminKennwortAendern.adminBenutzernameData = textField_adminBenutzernameResult.getValue();
					
					if(textField_adminBenutzernameResult.getValue().equals("") || passwordField_altesKennwortReslut.getValue().equals("") ||
							passwordField_neuesKennwortResult.getValue().equals("") ||
							passwordField_neseKennwortBestaetigenReslut.getValue().equals("")) {
						
						Notification.show(" Eine oder mehrere Angaben konnten nicht verarbeiten werden ");
						panel_Content.setCaption("admin kennwort ändern \\ Eine oder mehrere Angaben konnten nicht verarbeiten werden");
						
					}else{
						if(passwordField_neseKennwortBestaetigenReslut.getValue().equals(passwordField_neuesKennwortResult.getValue())){
							navigator.addView(Admin_NeuebenutzernameHinzufuegenBestaetigen.ADMIN_NEUE_BENUTZER_HINZUFUEGEN_BESTAETIGEN, new Admin_KennwortAendernBestaetigen());
							navigator.navigateTo(Admin_NeuebenutzernameHinzufuegenBestaetigen.ADMIN_NEUE_BENUTZER_HINZUFUEGEN_BESTAETIGEN);
						}else{
							Notification.show(" Eine oder mehrere Angaben konnten nicht verarbeiten werden ");
							panel_Content.setCaption("admin kennwort ändern \\ Eine oder mehrere Angaben konnten nicht verarbeiten werden");
						}
						
					}
					
				}
			});
		} catch (Exception e) {
			e.printStackTrace();
		}
		
		try {
			
			button_abmelden.addClickListener(new Button.ClickListener() {
				
				@Override
				public void buttonClick(ClickEvent event) {
					JrsiiUI.getCurrent().setContent(new Login());
					
				}
			});
		} catch (Exception e) {
			e.printStackTrace();
		}


		
	}

	@Override
	public void enter(ViewChangeEvent event) {
		// TODO Auto-generated method stub
		Notification.show("Admin kennwort Änderen");
		panel_Content.setCaption("admin kennwort ändern");
		navigator = event.getNavigator();
		
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// horizontalLayout_Main
		horizontalLayout_Main = buildHorizontalLayout_Main();
		mainLayout.addComponent(horizontalLayout_Main,
				"top:0.0px;right:-5.0px;bottom:0.0px;left:0.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_Main() {
		// common part: create layout
		horizontalLayout_Main = new HorizontalLayout();
		horizontalLayout_Main.setImmediate(false);
		horizontalLayout_Main.setWidth("100.0%");
		horizontalLayout_Main.setHeight("100.0%");
		horizontalLayout_Main.setMargin(false);
		
		// verticalLayout_Left
		verticalLayout_Left = buildVerticalLayout_Left();
		horizontalLayout_Main.addComponent(verticalLayout_Left);
		horizontalLayout_Main.setExpandRatio(verticalLayout_Left, 0.45f);
		
		// verticalLayout_Right
		verticalLayout_Right = buildVerticalLayout_Right();
		horizontalLayout_Main.addComponent(verticalLayout_Right);
		horizontalLayout_Main.setExpandRatio(verticalLayout_Right, 1.0f);
		
		return horizontalLayout_Main;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_Left() {
		// common part: create layout
		verticalLayout_Left = new VerticalLayout();
		verticalLayout_Left.setImmediate(false);
		verticalLayout_Left.setWidth("100.0%");
		verticalLayout_Left.setHeight("100.0%");
		verticalLayout_Left.setMargin(false);
		
		// button_administrator
		button_administrator = new Button();
		button_administrator.setCaption("Administrator");
		button_administrator.setImmediate(true);
		button_administrator.setWidth("-1px");
		button_administrator.setHeight("-1px");
		verticalLayout_Left.addComponent(button_administrator);
		verticalLayout_Left.setExpandRatio(button_administrator, 1.0f);
		verticalLayout_Left.setComponentAlignment(button_administrator,
				new Alignment(34));
		
		// button_abmelden
		button_abmelden = new Button();
		button_abmelden.setCaption("Abmelden");
		button_abmelden.setImmediate(true);
		button_abmelden.setWidth("-1px");
		button_abmelden.setHeight("-1px");
		verticalLayout_Left.addComponent(button_abmelden);
		verticalLayout_Left.setExpandRatio(button_abmelden, 1.0f);
		verticalLayout_Left.setComponentAlignment(button_abmelden,
				new Alignment(6));
		
		return verticalLayout_Left;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_Right() {
		// common part: create layout
		verticalLayout_Right = new VerticalLayout();
		verticalLayout_Right.setImmediate(false);
		verticalLayout_Right.setWidth("100.0%");
		verticalLayout_Right.setHeight("100.0%");
		verticalLayout_Right.setMargin(false);
		
		// panel_Content
		panel_Content = buildPanel_Content();
		verticalLayout_Right.addComponent(panel_Content);
		verticalLayout_Right.setExpandRatio(panel_Content, 1.0f);
		
		return verticalLayout_Right;
	}

	@AutoGenerated
	private Panel buildPanel_Content() {
		// common part: create layout
		panel_Content = new Panel();
		panel_Content.setImmediate(false);
		panel_Content.setWidth("100.0%");
		panel_Content.setHeight("100.0%");
		
		// verticalLayout_Panel
		verticalLayout_Panel = buildVerticalLayout_Panel();
		panel_Content.setContent(verticalLayout_Panel);
		
		return panel_Content;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_Panel() {
		// common part: create layout
		verticalLayout_Panel = new VerticalLayout();
		verticalLayout_Panel.setImmediate(false);
		verticalLayout_Panel.setWidth("100.0%");
		verticalLayout_Panel.setHeight("100.0%");
		verticalLayout_Panel.setMargin(false);
		
		// label_AdminBenutzername
		label_AdminBenutzername = new Label();
		label_AdminBenutzername.setImmediate(false);
		label_AdminBenutzername.setWidth("-1px");
		label_AdminBenutzername.setHeight("-1px");
		label_AdminBenutzername.setValue("admin benutzername");
		verticalLayout_Panel.addComponent(label_AdminBenutzername);
		verticalLayout_Panel.setComponentAlignment(label_AdminBenutzername,
				new Alignment(48));
		
		// textField_adminBenutzernameResult
		textField_adminBenutzernameResult = new TextField();
		textField_adminBenutzernameResult.setImmediate(false);
		textField_adminBenutzernameResult.setWidth("-1px");
		textField_adminBenutzernameResult.setHeight("-1px");
		verticalLayout_Panel.addComponent(textField_adminBenutzernameResult);
		verticalLayout_Panel.setComponentAlignment(
				textField_adminBenutzernameResult, new Alignment(20));
		
		// label_altesKennwortEingeben
		label_altesKennwortEingeben = new Label();
		label_altesKennwortEingeben.setImmediate(false);
		label_altesKennwortEingeben.setWidth("-1px");
		label_altesKennwortEingeben.setHeight("-1px");
		label_altesKennwortEingeben.setValue("altes kennwort eingeben");
		verticalLayout_Panel.addComponent(label_altesKennwortEingeben);
		verticalLayout_Panel.setComponentAlignment(label_altesKennwortEingeben,
				new Alignment(24));
		
		// passwordField_altesKennwortReslut
		passwordField_altesKennwortReslut = new PasswordField();
		passwordField_altesKennwortReslut.setImmediate(false);
		passwordField_altesKennwortReslut.setWidth("-1px");
		passwordField_altesKennwortReslut.setHeight("-1px");
		verticalLayout_Panel.addComponent(passwordField_altesKennwortReslut);
		verticalLayout_Panel.setComponentAlignment(
				passwordField_altesKennwortReslut, new Alignment(20));
		
		// label_neuesKennwortEingeben
		label_neuesKennwortEingeben = new Label();
		label_neuesKennwortEingeben.setImmediate(false);
		label_neuesKennwortEingeben.setWidth("-1px");
		label_neuesKennwortEingeben.setHeight("-1px");
		label_neuesKennwortEingeben.setValue("neues kennwort eingeben");
		verticalLayout_Panel.addComponent(label_neuesKennwortEingeben);
		verticalLayout_Panel.setComponentAlignment(label_neuesKennwortEingeben,
				new Alignment(24));
		
		// passwordField_neuesKennwortResult
		passwordField_neuesKennwortResult = new PasswordField();
		passwordField_neuesKennwortResult.setImmediate(false);
		passwordField_neuesKennwortResult.setWidth("-1px");
		passwordField_neuesKennwortResult.setHeight("-1px");
		verticalLayout_Panel.addComponent(passwordField_neuesKennwortResult);
		verticalLayout_Panel.setComponentAlignment(
				passwordField_neuesKennwortResult, new Alignment(20));
		
		// label_neuesKennwortBestaetigen
		label_neuesKennwortBestaetigen = new Label();
		label_neuesKennwortBestaetigen.setImmediate(false);
		label_neuesKennwortBestaetigen.setWidth("-1px");
		label_neuesKennwortBestaetigen.setHeight("-1px");
		label_neuesKennwortBestaetigen.setValue("neues kennwort bestätigen");
		verticalLayout_Panel.addComponent(label_neuesKennwortBestaetigen);
		verticalLayout_Panel.setComponentAlignment(
				label_neuesKennwortBestaetigen, new Alignment(24));
		
		// passwordField_neseKennwortBestaetigenReslut
		passwordField_neseKennwortBestaetigenReslut = new PasswordField();
		passwordField_neseKennwortBestaetigenReslut.setImmediate(false);
		passwordField_neseKennwortBestaetigenReslut.setWidth("-1px");
		passwordField_neseKennwortBestaetigenReslut.setHeight("-1px");
		verticalLayout_Panel
				.addComponent(passwordField_neseKennwortBestaetigenReslut);
		verticalLayout_Panel.setComponentAlignment(
				passwordField_neseKennwortBestaetigenReslut, new Alignment(20));
		
		// button_Zusenden
		button_Zusenden = new Button();
		button_Zusenden.setCaption("zusenden");
		button_Zusenden.setImmediate(true);
		button_Zusenden.setWidth("-1px");
		button_Zusenden.setHeight("-1px");
		verticalLayout_Panel.addComponent(button_Zusenden);
		verticalLayout_Panel.setComponentAlignment(button_Zusenden,
				new Alignment(48));
		
		return verticalLayout_Panel;
	}


}
