package com.jrsii.view.frontend;

import javax.persistence.EntityManager;

import com.jrsii.data.DataNeueBenutzerHinzufuegen;
import com.jrsii.entities.Benutzer;
import com.jrsii.main.JrsiiUI;
import com.jrsii.view.backend.AdminPage;
import com.vaadin.addon.jpacontainer.JPAContainerFactory;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.navigator.Navigator;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Notification;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;

public class Admin_NeuebenutzernameHinzufuegenBestaetigen extends
		CustomComponent implements View {
//	private final DataNeueBenutzerHinzufuegen dataNeueBenutzerHinzufuegen;
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;

	@AutoGenerated
	private HorizontalLayout horizontalLayout_Main;

	@AutoGenerated
	private VerticalLayout verticalLayout_Right;

	@AutoGenerated
	private Panel panel_Content;

	@AutoGenerated
	private VerticalLayout verticalLayout_Panel;

	@AutoGenerated
	private GridLayout gridLayout_Panel;

	@AutoGenerated
	private Button button_Hinzufuegen;

	@AutoGenerated
	private Label label_GeburtsdatumResult;

	@AutoGenerated
	private Label label_Geburtsdatum;

	@AutoGenerated
	private Label label_KennwortResult;

	@AutoGenerated
	private Label label_Kennwort;

	@AutoGenerated
	private Label label_BenutzernameResult;

	@AutoGenerated
	private Label label_Benutzername;

	@AutoGenerated
	private Label label_StellungResult;

	@AutoGenerated
	private Label label_Stellung;

	@AutoGenerated
	private Label label_NachnameResult;

	@AutoGenerated
	private Label label_Nachname;

	@AutoGenerated
	private Label label_VornamereResults;

	@AutoGenerated
	private Label label_Vorname;

	@AutoGenerated
	private VerticalLayout verticalLayout_Left;

	@AutoGenerated
	private Button button_abmelden;

	@AutoGenerated
	private Button button_neueBenutzerHinzufgen;

	//	protected static final String ADMIN_NEUE_BENUTZER_HINZUFUEGEN = "adminNeueBenutzerHinzufuegen";
	public static final String ADMIN_NEUE_BENUTZER_HINZUFUEGEN_BESTAETIGEN = "AdminNeuebenutzernameHinzufuegenBestaetigen";
	private Benutzer benutzer;
	public Navigator navigator;


	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public Admin_NeuebenutzernameHinzufuegenBestaetigen() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
 		label_VornamereResults.setValue(DataNeueBenutzerHinzufuegen.dataVornameStr);
		label_NachnameResult.setValue(DataNeueBenutzerHinzufuegen.dataNachnameStr);
		label_StellungResult.setValue(DataNeueBenutzerHinzufuegen.dataStellungStr);
		label_BenutzernameResult.setValue(DataNeueBenutzerHinzufuegen.dataBenutzernameStr);
		label_KennwortResult.setValue(DataNeueBenutzerHinzufuegen.dataKennwortStr);
		label_GeburtsdatumResult.setValue(DataNeueBenutzerHinzufuegen.dataGeburtsdatumStr);
	
		benutzer = new Benutzer();
		benutzer.setVorname(label_VornamereResults.getValue());
		benutzer.setNachname(label_NachnameResult.getValue());
		benutzer.setStellung(label_VornamereResults.getValue());
		benutzer.setBenutzername(label_BenutzernameResult.getValue());
		benutzer.setKennwort(label_KennwortResult.getValue());
		benutzer.setGeburtsdatum(DataNeueBenutzerHinzufuegen.dataGeburtsdatumDate);
		benutzer.setEnabled(true);
		
		try {
			button_Hinzufuegen.addClickListener(new Button.ClickListener() {
				
				@Override
				public void buttonClick(ClickEvent event) {
					EntityManager em = JPAContainerFactory.createEntityManagerForPersistenceUnit("jrsdbmysql");
					em.getTransaction().begin();
					em.persist(benutzer);
					em.getTransaction().commit();
					Notification.show("the entry has been entered");
					JrsiiUI.getCurrent().setContent(new AdminPage());
					
				}
			});
		} catch (Exception e) {
			e.printStackTrace();
		}
		
		try {
			
			button_abmelden.addClickListener(new Button.ClickListener() {
				
				@Override
				public void buttonClick(ClickEvent event) {
					JrsiiUI.getCurrent().setContent(new Login());
					
				}
			});
		} catch (Exception e) {
			e.printStackTrace();
		}


	}
	
	@Override
	public void enter(ViewChangeEvent event) {
		navigator=event.getNavigator();
				
	}
	
	
	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// horizontalLayout_Main
		horizontalLayout_Main = buildHorizontalLayout_Main();
		mainLayout.addComponent(horizontalLayout_Main,
				"top:0.0px;right:-5.0px;bottom:0.0px;left:0.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_Main() {
		// common part: create layout
		horizontalLayout_Main = new HorizontalLayout();
		horizontalLayout_Main.setImmediate(false);
		horizontalLayout_Main.setWidth("100.0%");
		horizontalLayout_Main.setHeight("100.0%");
		horizontalLayout_Main.setMargin(false);
		
		// verticalLayout_Left
		verticalLayout_Left = buildVerticalLayout_Left();
		horizontalLayout_Main.addComponent(verticalLayout_Left);
		horizontalLayout_Main.setExpandRatio(verticalLayout_Left, 0.45f);
		
		// verticalLayout_Right
		verticalLayout_Right = buildVerticalLayout_Right();
		horizontalLayout_Main.addComponent(verticalLayout_Right);
		horizontalLayout_Main.setExpandRatio(verticalLayout_Right, 1.0f);
		
		return horizontalLayout_Main;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_Left() {
		// common part: create layout
		verticalLayout_Left = new VerticalLayout();
		verticalLayout_Left.setImmediate(false);
		verticalLayout_Left.setWidth("100.0%");
		verticalLayout_Left.setHeight("100.0%");
		verticalLayout_Left.setMargin(false);
		
		// button_neueBenutzerHinzufgen
		button_neueBenutzerHinzufgen = new Button();
		button_neueBenutzerHinzufgen.setCaption("Neue benutzer hinzufügen");
		button_neueBenutzerHinzufgen.setImmediate(true);
		button_neueBenutzerHinzufgen.setWidth("-1px");
		button_neueBenutzerHinzufgen.setHeight("-1px");
		verticalLayout_Left.addComponent(button_neueBenutzerHinzufgen);
		verticalLayout_Left.setExpandRatio(button_neueBenutzerHinzufgen, 1.0f);
		verticalLayout_Left.setComponentAlignment(button_neueBenutzerHinzufgen,
				new Alignment(34));
		
		// button_abmelden
		button_abmelden = new Button();
		button_abmelden.setCaption("Abmelden");
		button_abmelden.setImmediate(true);
		button_abmelden.setWidth("-1px");
		button_abmelden.setHeight("-1px");
		verticalLayout_Left.addComponent(button_abmelden);
		verticalLayout_Left.setExpandRatio(button_abmelden, 1.0f);
		verticalLayout_Left.setComponentAlignment(button_abmelden,
				new Alignment(6));
		
		return verticalLayout_Left;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_Right() {
		// common part: create layout
		verticalLayout_Right = new VerticalLayout();
		verticalLayout_Right.setImmediate(false);
		verticalLayout_Right.setWidth("100.0%");
		verticalLayout_Right.setHeight("100.0%");
		verticalLayout_Right.setMargin(false);
		
		// panel_Content
		panel_Content = buildPanel_Content();
		verticalLayout_Right.addComponent(panel_Content);
		verticalLayout_Right.setExpandRatio(panel_Content, 1.0f);
		
		return verticalLayout_Right;
	}

	@AutoGenerated
	private Panel buildPanel_Content() {
		// common part: create layout
		panel_Content = new Panel();
		panel_Content.setImmediate(false);
		panel_Content.setWidth("100.0%");
		panel_Content.setHeight("100.0%");
		
		// verticalLayout_Panel
		verticalLayout_Panel = buildVerticalLayout_Panel();
		panel_Content.setContent(verticalLayout_Panel);
		
		return panel_Content;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_Panel() {
		// common part: create layout
		verticalLayout_Panel = new VerticalLayout();
		verticalLayout_Panel.setImmediate(false);
		verticalLayout_Panel.setWidth("100.0%");
		verticalLayout_Panel.setHeight("100.0%");
		verticalLayout_Panel.setMargin(false);
		
		// gridLayout_Panel
		gridLayout_Panel = buildGridLayout_Panel();
		verticalLayout_Panel.addComponent(gridLayout_Panel);
		verticalLayout_Panel.setExpandRatio(gridLayout_Panel, 1.0f);
		verticalLayout_Panel.setComponentAlignment(gridLayout_Panel,
				new Alignment(48));
		
		return verticalLayout_Panel;
	}

	@AutoGenerated
	private GridLayout buildGridLayout_Panel() {
		// common part: create layout
		gridLayout_Panel = new GridLayout();
		gridLayout_Panel.setImmediate(false);
		gridLayout_Panel.setWidth("100.0%");
		gridLayout_Panel.setHeight("100.0%");
		gridLayout_Panel.setMargin(false);
		gridLayout_Panel.setColumns(2);
		gridLayout_Panel.setRows(9);
		
		// label_Vorname
		label_Vorname = new Label();
		label_Vorname.setImmediate(false);
		label_Vorname.setWidth("-1px");
		label_Vorname.setHeight("-1px");
		label_Vorname.setValue("vorname");
		gridLayout_Panel.addComponent(label_Vorname, 0, 0);
		gridLayout_Panel
				.setComponentAlignment(label_Vorname, new Alignment(48));
		
		// label_VornamereResults
		label_VornamereResults = new Label();
		label_VornamereResults.setImmediate(false);
		label_VornamereResults.setWidth("-1px");
		label_VornamereResults.setHeight("-1px");
		label_VornamereResults.setValue("-");
		gridLayout_Panel.addComponent(label_VornamereResults, 1, 0);
		gridLayout_Panel.setComponentAlignment(label_VornamereResults,
				new Alignment(48));
		
		// label_Nachname
		label_Nachname = new Label();
		label_Nachname.setImmediate(false);
		label_Nachname.setWidth("-1px");
		label_Nachname.setHeight("-1px");
		label_Nachname.setValue("nachname");
		gridLayout_Panel.addComponent(label_Nachname, 0, 1);
		gridLayout_Panel.setComponentAlignment(label_Nachname,
				new Alignment(48));
		
		// label_NachnameResult
		label_NachnameResult = new Label();
		label_NachnameResult.setImmediate(false);
		label_NachnameResult.setWidth("-1px");
		label_NachnameResult.setHeight("-1px");
		label_NachnameResult.setValue("-");
		gridLayout_Panel.addComponent(label_NachnameResult, 1, 1);
		gridLayout_Panel.setComponentAlignment(label_NachnameResult,
				new Alignment(48));
		
		// label_Stellung
		label_Stellung = new Label();
		label_Stellung.setImmediate(false);
		label_Stellung.setWidth("-1px");
		label_Stellung.setHeight("-1px");
		label_Stellung.setValue("stellung");
		gridLayout_Panel.addComponent(label_Stellung, 0, 2);
		gridLayout_Panel.setComponentAlignment(label_Stellung,
				new Alignment(48));
		
		// label_StellungResult
		label_StellungResult = new Label();
		label_StellungResult.setImmediate(false);
		label_StellungResult.setWidth("-1px");
		label_StellungResult.setHeight("-1px");
		label_StellungResult.setValue("-");
		gridLayout_Panel.addComponent(label_StellungResult, 1, 2);
		gridLayout_Panel.setComponentAlignment(label_StellungResult,
				new Alignment(48));
		
		// label_Benutzername
		label_Benutzername = new Label();
		label_Benutzername.setImmediate(false);
		label_Benutzername.setWidth("-1px");
		label_Benutzername.setHeight("-1px");
		label_Benutzername.setValue("benutzername");
		gridLayout_Panel.addComponent(label_Benutzername, 0, 3);
		gridLayout_Panel.setComponentAlignment(label_Benutzername,
				new Alignment(48));
		
		// label_BenutzernameResult
		label_BenutzernameResult = new Label();
		label_BenutzernameResult.setImmediate(false);
		label_BenutzernameResult.setWidth("-1px");
		label_BenutzernameResult.setHeight("-1px");
		label_BenutzernameResult.setValue("-");
		gridLayout_Panel.addComponent(label_BenutzernameResult, 1, 3);
		gridLayout_Panel.setComponentAlignment(label_BenutzernameResult,
				new Alignment(48));
		
		// label_Kennwort
		label_Kennwort = new Label();
		label_Kennwort.setImmediate(false);
		label_Kennwort.setWidth("-1px");
		label_Kennwort.setHeight("-1px");
		label_Kennwort.setValue("kennwort");
		gridLayout_Panel.addComponent(label_Kennwort, 0, 4);
		gridLayout_Panel.setComponentAlignment(label_Kennwort,
				new Alignment(48));
		
		// label_KennwortResult
		label_KennwortResult = new Label();
		label_KennwortResult.setImmediate(false);
		label_KennwortResult.setWidth("-1px");
		label_KennwortResult.setHeight("-1px");
		label_KennwortResult.setValue("-");
		gridLayout_Panel.addComponent(label_KennwortResult, 1, 4);
		gridLayout_Panel.setComponentAlignment(label_KennwortResult,
				new Alignment(48));
		
		// label_Geburtsdatum
		label_Geburtsdatum = new Label();
		label_Geburtsdatum.setImmediate(false);
		label_Geburtsdatum.setWidth("-1px");
		label_Geburtsdatum.setHeight("18px");
		label_Geburtsdatum.setValue("geburtsdatum");
		gridLayout_Panel.addComponent(label_Geburtsdatum, 0, 5);
		gridLayout_Panel.setComponentAlignment(label_Geburtsdatum,
				new Alignment(48));
		
		// label_GeburtsdatumResult
		label_GeburtsdatumResult = new Label();
		label_GeburtsdatumResult.setImmediate(false);
		label_GeburtsdatumResult.setWidth("-1px");
		label_GeburtsdatumResult.setHeight("-1px");
		label_GeburtsdatumResult.setValue("-");
		gridLayout_Panel.addComponent(label_GeburtsdatumResult, 1, 5);
		gridLayout_Panel.setComponentAlignment(label_GeburtsdatumResult,
				new Alignment(48));
		
		// button_Hinzufuegen
		button_Hinzufuegen = new Button();
		button_Hinzufuegen.setCaption("hinzufügen");
		button_Hinzufuegen.setImmediate(true);
		button_Hinzufuegen.setWidth("-1px");
		button_Hinzufuegen.setHeight("-1px");
		gridLayout_Panel.addComponent(button_Hinzufuegen, 0, 7);
		gridLayout_Panel.setComponentAlignment(button_Hinzufuegen,
				new Alignment(34));
		
		return gridLayout_Panel;
	}

}
