package com.jrsii.view.frontend;


import javax.persistence.EntityManager;
import javax.persistence.Query;

import com.jrsii.entities.Benutzer;
import com.jrsii.main.JrsiiUI;
import com.jrsii.view.backend.AdminPage;
import com.vaadin.addon.jpacontainer.JPAContainerFactory;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.navigator.Navigator;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Notification;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;


public class Admin_BenutzerEntfernen extends CustomComponent implements View {
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;

	@AutoGenerated
	private HorizontalLayout horizontalLayout_Main;

	@AutoGenerated
	private VerticalLayout verticalLayout_Right;

	@AutoGenerated
	private Panel panel_Content;

	@AutoGenerated
	private VerticalLayout verticalLayout_Panel;

	@AutoGenerated
	private Button button_Entfernen;

	@AutoGenerated
	private GridLayout gridLayout_2;

	@AutoGenerated
	private TextField textField_GeburtsdatumResult;

	@AutoGenerated
	private Label label_Geburtsdatumresult;

	@AutoGenerated
	private TextField textField_StelleResult;

	@AutoGenerated
	private Label label_StelleResult;

	@AutoGenerated
	private TextField textField_NachnameResult;

	@AutoGenerated
	private Label label_NachnameResult;

	@AutoGenerated
	private TextField textField_VornameResult;

	@AutoGenerated
	private Label label_VornameResult;

	@AutoGenerated
	private TextField textField_BenutzernameResult;

	@AutoGenerated
	private Label label_BenutzernameResult;

	@AutoGenerated
	private Label label_Ergebnis;

	@AutoGenerated
	private Button button_finden;

	@AutoGenerated
	private GridLayout gridLayout_1;

	@AutoGenerated
	private TextField textField_Buntzername;

	@AutoGenerated
	private Label label_Benutzername;

	@AutoGenerated
	private VerticalLayout verticalLayout_Left;

	@AutoGenerated
	private Button button_abmelden;

	@AutoGenerated
	private Button button_benutzerEntfernen;

	public Navigator navigator;
	public Benutzer benutzer;
	public String benutzernameStr = null;
	public static final String ADMIN_BENUTZER_EINTEFREN = "adminBenutzerEntfernen";
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public Admin_BenutzerEntfernen() {
		// TODO add user code here
		 buildMainLayout();
		 setCompositionRoot(mainLayout);
		 final  EntityManager em = JPAContainerFactory.createEntityManagerForPersistenceUnit("jrsdbmysql");
	
			button_finden.addClickListener(new Button.ClickListener() {
				
				@Override
				public void buttonClick(ClickEvent event) {
					benutzernameStr = textField_Buntzername.getValue();
					
					Query q = em.createQuery("FROM Benutzer b WHERE b.benutzername = ?1");
					q.setParameter(1, benutzernameStr);
					q.setMaxResults(1);
					
					try {
						benutzer = (Benutzer) q.getSingleResult();
						
						textField_BenutzernameResult.setValue(benutzer.getBenutzername());
						textField_VornameResult.setValue(benutzer.getVorname());
						textField_NachnameResult.setValue(benutzer.getNachname());
						textField_StelleResult.setValue(benutzer.getStellung());
						textField_GeburtsdatumResult.setValue(benutzer.getGeburtsdatum().toString());
						
					} catch (Exception e) {
						Notification.show(" you entered a wrong username");
						e.printStackTrace();
					}
					
					
				}
			});
			 
			
			button_Entfernen.addClickListener(new Button.ClickListener() {
				
				@Override
				public void buttonClick(ClickEvent event) {
					try {
						em.getTransaction().begin();
						em.remove(benutzer);
						em.getTransaction().commit();
						Notification.show(" the user \" "+benutzernameStr+" \" is deleted successfuly");
						JrsiiUI.getCurrent().setContent(new AdminPage());
					} catch (Exception e) {
						em.getTransaction().rollback();
						Notification.show(" the user has not been deleted successfully, please try again");
						e.printStackTrace();
					
					}
					
				}
			});
		
		
		
		try {
			
			button_abmelden.addClickListener(new Button.ClickListener() {
				
				@Override
				public void buttonClick(ClickEvent event) {
					JrsiiUI.getCurrent().setContent(new Login());
					
				}
			});
		} catch (Exception e) {
			e.printStackTrace();
		}

	}
	
	@Override
	public void enter(ViewChangeEvent event) {
		// TODO Auto-generated method stub
		 panel_Content.setCaption("Benutzer Entfernen");
		navigator = event.getNavigator();
		
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// horizontalLayout_Main
		horizontalLayout_Main = buildHorizontalLayout_Main();
		mainLayout.addComponent(horizontalLayout_Main,
				"top:0.0px;right:-5.0px;bottom:0.0px;left:0.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_Main() {
		// common part: create layout
		horizontalLayout_Main = new HorizontalLayout();
		horizontalLayout_Main.setImmediate(false);
		horizontalLayout_Main.setWidth("100.0%");
		horizontalLayout_Main.setHeight("100.0%");
		horizontalLayout_Main.setMargin(false);
		
		// verticalLayout_Left
		verticalLayout_Left = buildVerticalLayout_Left();
		horizontalLayout_Main.addComponent(verticalLayout_Left);
		horizontalLayout_Main.setExpandRatio(verticalLayout_Left, 0.45f);
		
		// verticalLayout_Right
		verticalLayout_Right = buildVerticalLayout_Right();
		horizontalLayout_Main.addComponent(verticalLayout_Right);
		horizontalLayout_Main.setExpandRatio(verticalLayout_Right, 1.0f);
		
		return horizontalLayout_Main;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_Left() {
		// common part: create layout
		verticalLayout_Left = new VerticalLayout();
		verticalLayout_Left.setImmediate(false);
		verticalLayout_Left.setWidth("100.0%");
		verticalLayout_Left.setHeight("100.0%");
		verticalLayout_Left.setMargin(false);
		
		// button_benutzerEntfernen
		button_benutzerEntfernen = new Button();
		button_benutzerEntfernen.setCaption("Benutzer erntfernen");
		button_benutzerEntfernen.setImmediate(true);
		button_benutzerEntfernen.setWidth("-1px");
		button_benutzerEntfernen.setHeight("-1px");
		verticalLayout_Left.addComponent(button_benutzerEntfernen);
		verticalLayout_Left.setExpandRatio(button_benutzerEntfernen, 1.0f);
		verticalLayout_Left.setComponentAlignment(button_benutzerEntfernen,
				new Alignment(34));
		
		// button_abmelden
		button_abmelden = new Button();
		button_abmelden.setCaption("Abmelden");
		button_abmelden.setImmediate(true);
		button_abmelden.setWidth("-1px");
		button_abmelden.setHeight("-1px");
		verticalLayout_Left.addComponent(button_abmelden);
		verticalLayout_Left.setExpandRatio(button_abmelden, 1.0f);
		verticalLayout_Left.setComponentAlignment(button_abmelden,
				new Alignment(6));
		
		return verticalLayout_Left;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_Right() {
		// common part: create layout
		verticalLayout_Right = new VerticalLayout();
		verticalLayout_Right.setImmediate(false);
		verticalLayout_Right.setWidth("100.0%");
		verticalLayout_Right.setHeight("100.0%");
		verticalLayout_Right.setMargin(false);
		
		// panel_Content
		panel_Content = buildPanel_Content();
		verticalLayout_Right.addComponent(panel_Content);
		verticalLayout_Right.setExpandRatio(panel_Content, 1.0f);
		
		return verticalLayout_Right;
	}

	@AutoGenerated
	private Panel buildPanel_Content() {
		// common part: create layout
		panel_Content = new Panel();
		panel_Content.setImmediate(false);
		panel_Content.setWidth("100.0%");
		panel_Content.setHeight("100.0%");
		
		// verticalLayout_Panel
		verticalLayout_Panel = buildVerticalLayout_Panel();
		panel_Content.setContent(verticalLayout_Panel);
		
		return panel_Content;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_Panel() {
		// common part: create layout
		verticalLayout_Panel = new VerticalLayout();
		verticalLayout_Panel.setImmediate(false);
		verticalLayout_Panel.setWidth("100.0%");
		verticalLayout_Panel.setHeight("100.0%");
		verticalLayout_Panel.setMargin(false);
		
		// gridLayout_1
		gridLayout_1 = buildGridLayout_1();
		verticalLayout_Panel.addComponent(gridLayout_1);
		verticalLayout_Panel.setExpandRatio(gridLayout_1, 1.0f);
		
		// button_finden
		button_finden = new Button();
		button_finden.setCaption("finden");
		button_finden.setImmediate(true);
		button_finden.setWidth("-1px");
		button_finden.setHeight("-1px");
		verticalLayout_Panel.addComponent(button_finden);
		verticalLayout_Panel.setComponentAlignment(button_finden,
				new Alignment(48));
		
		// label_Ergebnis
		label_Ergebnis = new Label();
		label_Ergebnis.setImmediate(false);
		label_Ergebnis.setWidth("-1px");
		label_Ergebnis.setHeight("-1px");
		label_Ergebnis.setValue("-- ergebnis --");
		verticalLayout_Panel.addComponent(label_Ergebnis);
		verticalLayout_Panel.setComponentAlignment(label_Ergebnis,
				new Alignment(48));
		
		// gridLayout_2
		gridLayout_2 = buildGridLayout_2();
		verticalLayout_Panel.addComponent(gridLayout_2);
		verticalLayout_Panel.setExpandRatio(gridLayout_2, 1.0f);
		verticalLayout_Panel.setComponentAlignment(gridLayout_2, new Alignment(
				48));
		
		// button_Entfernen
		button_Entfernen = new Button();
		button_Entfernen.setCaption("entfernen");
		button_Entfernen.setImmediate(true);
		button_Entfernen.setWidth("-1px");
		button_Entfernen.setHeight("-1px");
		verticalLayout_Panel.addComponent(button_Entfernen);
		verticalLayout_Panel.setComponentAlignment(button_Entfernen,
				new Alignment(20));
		
		return verticalLayout_Panel;
	}

	@AutoGenerated
	private GridLayout buildGridLayout_1() {
		// common part: create layout
		gridLayout_1 = new GridLayout();
		gridLayout_1.setImmediate(false);
		gridLayout_1.setWidth("100.0%");
		gridLayout_1.setHeight("100.0%");
		gridLayout_1.setMargin(false);
		gridLayout_1.setColumns(2);
		
		// label_Benutzername
		label_Benutzername = new Label();
		label_Benutzername.setImmediate(false);
		label_Benutzername.setWidth("-1px");
		label_Benutzername.setHeight("-1px");
		label_Benutzername.setValue("benutzername eingeben ");
		gridLayout_1.addComponent(label_Benutzername, 0, 0);
		gridLayout_1.setComponentAlignment(label_Benutzername,
				new Alignment(48));
		
		// textField_Buntzername
		textField_Buntzername = new TextField();
		textField_Buntzername.setImmediate(false);
		textField_Buntzername.setWidth("-1px");
		textField_Buntzername.setHeight("-1px");
		gridLayout_1.addComponent(textField_Buntzername, 1, 0);
		gridLayout_1.setComponentAlignment(textField_Buntzername,
				new Alignment(48));
		
		return gridLayout_1;
	}

	@AutoGenerated
	private GridLayout buildGridLayout_2() {
		// common part: create layout
		gridLayout_2 = new GridLayout();
		gridLayout_2.setImmediate(false);
		gridLayout_2.setWidth("100.0%");
		gridLayout_2.setHeight("100.0%");
		gridLayout_2.setMargin(false);
		gridLayout_2.setColumns(2);
		gridLayout_2.setRows(5);
		
		// label_BenutzernameResult
		label_BenutzernameResult = new Label();
		label_BenutzernameResult.setImmediate(false);
		label_BenutzernameResult.setWidth("-1px");
		label_BenutzernameResult.setHeight("-1px");
		label_BenutzernameResult.setValue("benutzername");
		gridLayout_2.addComponent(label_BenutzernameResult, 0, 0);
		gridLayout_2.setComponentAlignment(label_BenutzernameResult,
				new Alignment(48));
		
		// textField_BenutzernameResult
		textField_BenutzernameResult = new TextField();
		textField_BenutzernameResult.setImmediate(false);
		textField_BenutzernameResult.setWidth("-1px");
		textField_BenutzernameResult.setHeight("-1px");
		gridLayout_2.addComponent(textField_BenutzernameResult, 1, 0);
		gridLayout_2.setComponentAlignment(textField_BenutzernameResult,
				new Alignment(48));
		
		// label_VornameResult
		label_VornameResult = new Label();
		label_VornameResult.setImmediate(false);
		label_VornameResult.setWidth("-1px");
		label_VornameResult.setHeight("-1px");
		label_VornameResult.setValue("vorname");
		gridLayout_2.addComponent(label_VornameResult, 0, 1);
		gridLayout_2.setComponentAlignment(label_VornameResult, new Alignment(
				48));
		
		// textField_VornameResult
		textField_VornameResult = new TextField();
		textField_VornameResult.setImmediate(false);
		textField_VornameResult.setWidth("-1px");
		textField_VornameResult.setHeight("-1px");
		gridLayout_2.addComponent(textField_VornameResult, 1, 1);
		gridLayout_2.setComponentAlignment(textField_VornameResult,
				new Alignment(48));
		
		// label_NachnameResult
		label_NachnameResult = new Label();
		label_NachnameResult.setImmediate(false);
		label_NachnameResult.setWidth("-1px");
		label_NachnameResult.setHeight("-1px");
		label_NachnameResult.setValue("nachname");
		gridLayout_2.addComponent(label_NachnameResult, 0, 2);
		gridLayout_2.setComponentAlignment(label_NachnameResult, new Alignment(
				48));
		
		// textField_NachnameResult
		textField_NachnameResult = new TextField();
		textField_NachnameResult.setImmediate(false);
		textField_NachnameResult.setWidth("-1px");
		textField_NachnameResult.setHeight("-1px");
		gridLayout_2.addComponent(textField_NachnameResult, 1, 2);
		gridLayout_2.setComponentAlignment(textField_NachnameResult,
				new Alignment(48));
		
		// label_StelleResult
		label_StelleResult = new Label();
		label_StelleResult.setImmediate(false);
		label_StelleResult.setWidth("-1px");
		label_StelleResult.setHeight("-1px");
		label_StelleResult.setValue("stelle");
		gridLayout_2.addComponent(label_StelleResult, 0, 3);
		gridLayout_2.setComponentAlignment(label_StelleResult,
				new Alignment(48));
		
		// textField_StelleResult
		textField_StelleResult = new TextField();
		textField_StelleResult.setImmediate(false);
		textField_StelleResult.setWidth("-1px");
		textField_StelleResult.setHeight("-1px");
		gridLayout_2.addComponent(textField_StelleResult, 1, 3);
		gridLayout_2.setComponentAlignment(textField_StelleResult,
				new Alignment(48));
		
		// label_Geburtsdatumresult
		label_Geburtsdatumresult = new Label();
		label_Geburtsdatumresult.setImmediate(false);
		label_Geburtsdatumresult.setWidth("-1px");
		label_Geburtsdatumresult.setHeight("-1px");
		label_Geburtsdatumresult.setValue("geburtsdatum");
		gridLayout_2.addComponent(label_Geburtsdatumresult, 0, 4);
		gridLayout_2.setComponentAlignment(label_Geburtsdatumresult,
				new Alignment(48));
		
		// textField_GeburtsdatumResult
		textField_GeburtsdatumResult = new TextField();
		textField_GeburtsdatumResult.setImmediate(false);
		textField_GeburtsdatumResult.setWidth("-1px");
		textField_GeburtsdatumResult.setHeight("-1px");
		gridLayout_2.addComponent(textField_GeburtsdatumResult, 1, 4);
		gridLayout_2.setComponentAlignment(textField_GeburtsdatumResult,
				new Alignment(48));
		
		return gridLayout_2;
	}

}
