package com.jrsii.view.frontend;

import javax.persistence.EntityManager;

import com.jrsii.data.DataAdminKennwortAendern;
import com.jrsii.data.DataLogin;
import com.jrsii.entities.Benutzer;
import com.jrsii.main.JrsiiUI;
import com.jrsii.view.backend.AdminPage;
import com.vaadin.addon.jpacontainer.JPAContainerFactory;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Notification;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;

public class Admin_KennwortAendernBestaetigen extends CustomComponent implements View {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */


	@AutoGenerated
	private AbsoluteLayout mainLayout;

	@AutoGenerated
	private HorizontalLayout horizontalLayout_Main;

	@AutoGenerated
	private VerticalLayout verticalLayout_Right;

	@AutoGenerated
	private Panel panel_Content;

	@AutoGenerated
	private VerticalLayout verticalLayout_Panel;

	@AutoGenerated
	private Button button_Hinzufuegen;

	@AutoGenerated
	private Label label_neuesKennwortResult;

	@AutoGenerated
	private Label label_neuesKennwortEingeben;

	@AutoGenerated
	private Label label_alteskennwortResult;

	@AutoGenerated
	private Label label_altesKennwortEingeben;

	@AutoGenerated
	private VerticalLayout verticalLayout_Left;

	@AutoGenerated
	private Button button_abmelden;

	@AutoGenerated
	private Button button_administrator;

	private Benutzer benutzer;

	public static final String ADMIN_KENNWORT_AENDERN_BESTAETIGEN = "adminKennwortAendernBestaetigen";

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public Admin_KennwortAendernBestaetigen() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
        label_alteskennwortResult.setValue(DataAdminKennwortAendern.adminAltesKennwortData);
        label_neuesKennwortResult.setValue(DataAdminKennwortAendern.adminNeuesKennwortData);
		
		button_Hinzufuegen.addClickListener(new Button.ClickListener() {
			
			@Override
			public void buttonClick(ClickEvent event) {
			 
             EntityManager em = JPAContainerFactory.createEntityManagerForPersistenceUnit("jrsdbmysql");
             benutzer = em.find(Benutzer.class, DataLogin.dataBenutzername);
             try {
				em.getTransaction().begin();
				benutzer.setKennwort(DataAdminKennwortAendern.adminNeuesKennwortData);
				em.getTransaction().commit();
			} catch (Exception e) {
				em.getTransaction().rollback();
				e.printStackTrace();
			}
             Notification.show("the entry has been entered");
             JrsiiUI.getCurrent().setContent(new AdminPage());
             
			}
		});
		
		try {
			
			button_abmelden.addClickListener(new Button.ClickListener() {
				
				@Override
				public void buttonClick(ClickEvent event) {
					JrsiiUI.getCurrent().setContent(new Login());
					
				}
			});
		} catch (Exception e) {
			e.printStackTrace();
		}
		// TODO add user code here ye karai inja mished kard, aaa ye karaii onja
		
	}

	@Override
	public void enter(ViewChangeEvent event) {
		// TODO Auto-generated method stub
		Notification.show("Admin kennwort Änderen Bestätigen");
		panel_Content.setCaption("admin kennwort ändern / Bestätigung");
		
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// horizontalLayout_Main
		horizontalLayout_Main = buildHorizontalLayout_Main();
		mainLayout.addComponent(horizontalLayout_Main,
				"top:0.0px;right:-5.0px;bottom:0.0px;left:0.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_Main() {
		// common part: create layout
		horizontalLayout_Main = new HorizontalLayout();
		horizontalLayout_Main.setImmediate(false);
		horizontalLayout_Main.setWidth("100.0%");
		horizontalLayout_Main.setHeight("100.0%");
		horizontalLayout_Main.setMargin(false);
		
		// verticalLayout_Left
		verticalLayout_Left = buildVerticalLayout_Left();
		horizontalLayout_Main.addComponent(verticalLayout_Left);
		horizontalLayout_Main.setExpandRatio(verticalLayout_Left, 0.45f);
		
		// verticalLayout_Right
		verticalLayout_Right = buildVerticalLayout_Right();
		horizontalLayout_Main.addComponent(verticalLayout_Right);
		horizontalLayout_Main.setExpandRatio(verticalLayout_Right, 1.0f);
		
		return horizontalLayout_Main;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_Left() {
		// common part: create layout
		verticalLayout_Left = new VerticalLayout();
		verticalLayout_Left.setImmediate(false);
		verticalLayout_Left.setWidth("100.0%");
		verticalLayout_Left.setHeight("100.0%");
		verticalLayout_Left.setMargin(false);
		
		// button_administrator
		button_administrator = new Button();
		button_administrator.setCaption("Administrator");
		button_administrator.setImmediate(true);
		button_administrator.setWidth("-1px");
		button_administrator.setHeight("-1px");
		verticalLayout_Left.addComponent(button_administrator);
		verticalLayout_Left.setExpandRatio(button_administrator, 1.0f);
		verticalLayout_Left.setComponentAlignment(button_administrator,
				new Alignment(34));
		
		// button_abmelden
		button_abmelden = new Button();
		button_abmelden.setCaption("Abmelden");
		button_abmelden.setImmediate(true);
		button_abmelden.setWidth("-1px");
		button_abmelden.setHeight("-1px");
		verticalLayout_Left.addComponent(button_abmelden);
		verticalLayout_Left.setExpandRatio(button_abmelden, 1.0f);
		verticalLayout_Left.setComponentAlignment(button_abmelden,
				new Alignment(6));
		
		return verticalLayout_Left;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_Right() {
		// common part: create layout
		verticalLayout_Right = new VerticalLayout();
		verticalLayout_Right.setImmediate(false);
		verticalLayout_Right.setWidth("100.0%");
		verticalLayout_Right.setHeight("100.0%");
		verticalLayout_Right.setMargin(false);
		
		// panel_Content
		panel_Content = buildPanel_Content();
		verticalLayout_Right.addComponent(panel_Content);
		verticalLayout_Right.setExpandRatio(panel_Content, 1.0f);
		
		return verticalLayout_Right;
	}

	@AutoGenerated
	private Panel buildPanel_Content() {
		// common part: create layout
		panel_Content = new Panel();
		panel_Content.setImmediate(false);
		panel_Content.setWidth("100.0%");
		panel_Content.setHeight("100.0%");
		
		// verticalLayout_Panel
		verticalLayout_Panel = buildVerticalLayout_Panel();
		panel_Content.setContent(verticalLayout_Panel);
		
		return panel_Content;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_Panel() {
		// common part: create layout
		verticalLayout_Panel = new VerticalLayout();
		verticalLayout_Panel.setImmediate(false);
		verticalLayout_Panel.setWidth("100.0%");
		verticalLayout_Panel.setHeight("100.0%");
		verticalLayout_Panel.setMargin(false);
		
		// label_altesKennwortEingeben
		label_altesKennwortEingeben = new Label();
		label_altesKennwortEingeben.setImmediate(false);
		label_altesKennwortEingeben.setWidth("-1px");
		label_altesKennwortEingeben.setHeight("-1px");
		label_altesKennwortEingeben.setValue("altes kennwort");
		verticalLayout_Panel.addComponent(label_altesKennwortEingeben);
		verticalLayout_Panel.setExpandRatio(label_altesKennwortEingeben, 1.0f);
		verticalLayout_Panel.setComponentAlignment(label_altesKennwortEingeben,
				new Alignment(24));
		
		// label_alteskennwortResult
		label_alteskennwortResult = new Label();
		label_alteskennwortResult.setImmediate(false);
		label_alteskennwortResult.setWidth("-1px");
		label_alteskennwortResult.setHeight("-1px");
		label_alteskennwortResult.setValue("-");
		verticalLayout_Panel.addComponent(label_alteskennwortResult);
		verticalLayout_Panel.setExpandRatio(label_alteskennwortResult, 1.0f);
		verticalLayout_Panel.setComponentAlignment(label_alteskennwortResult,
				new Alignment(20));
		
		// label_neuesKennwortEingeben
		label_neuesKennwortEingeben = new Label();
		label_neuesKennwortEingeben.setImmediate(false);
		label_neuesKennwortEingeben.setWidth("-1px");
		label_neuesKennwortEingeben.setHeight("-1px");
		label_neuesKennwortEingeben.setValue("neues kennwort");
		verticalLayout_Panel.addComponent(label_neuesKennwortEingeben);
		verticalLayout_Panel.setExpandRatio(label_neuesKennwortEingeben, 1.0f);
		verticalLayout_Panel.setComponentAlignment(label_neuesKennwortEingeben,
				new Alignment(24));
		
		// label_neuesKennwortResult
		label_neuesKennwortResult = new Label();
		label_neuesKennwortResult.setImmediate(false);
		label_neuesKennwortResult.setWidth("-1px");
		label_neuesKennwortResult.setHeight("-1px");
		label_neuesKennwortResult.setValue("-");
		verticalLayout_Panel.addComponent(label_neuesKennwortResult);
		verticalLayout_Panel.setExpandRatio(label_neuesKennwortResult, 1.0f);
		verticalLayout_Panel.setComponentAlignment(label_neuesKennwortResult,
				new Alignment(20));
		
		// button_Hinzufuegen
		button_Hinzufuegen = new Button();
		button_Hinzufuegen.setCaption("hinzufügen");
		button_Hinzufuegen.setImmediate(true);
		button_Hinzufuegen.setWidth("-1px");
		button_Hinzufuegen.setHeight("-1px");
		verticalLayout_Panel.addComponent(button_Hinzufuegen);
		verticalLayout_Panel.setExpandRatio(button_Hinzufuegen, 1.0f);
		verticalLayout_Panel.setComponentAlignment(button_Hinzufuegen,
				new Alignment(48));
		
		return verticalLayout_Panel;
	}


}
