package com.jrsii.entities;

// default package
// Generated Jan 31, 2014 3:40:33 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.NamedQuery;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Adressgruppen generated by hbm2java
 */
@Entity //(name = "adressgruppen")
//@Table(name = "adressgruppen" , catalog = "jrsdbmysql" )
//@NamedQuery(name = "mazyTestQ", query = "FROM Adressgruppen ag WHERE ag.name LIKE :adressgruppeName")
public class Adressgruppen implements java.io.Serializable {

	private int id;
	private String name;
	private Boolean geschützt;
	private Boolean schüler;
	private Boolean student;
//	private Set adressgruppenverweises = new HashSet(0);

	public Adressgruppen() {
	}

	public Adressgruppen(int id) {
		this.id = id;
	}

//	public Adressgruppen(int id, String name, Boolean geschützt,
//			Boolean schüler, Boolean student, Set adressgruppenverweises) {
//		this.id = id;
//		this.name = name;
//		this.geschützt = geschützt;
//		this.schüler = schüler;
//		this.student = student;
//		this.adressgruppenverweises = adressgruppenverweises;
//	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
//	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}
	
	public void setId(int id) {
		this.id = id;
	}
//	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
//	@Column(name = "geschützt")
	public Boolean getGeschützt() {
		return this.geschützt;
	}

	public void setGeschützt(Boolean geschützt) {
		this.geschützt = geschützt;
	}
//	@Column(name = "schüler")
	public Boolean getSchüler() {
		return this.schüler;
	}

	public void setSchüler(Boolean schüler) {
		this.schüler = schüler;
	}
//	@Column(name = "student")
	public Boolean getStudent() {
		return this.student;
	}

	public void setStudent(Boolean student) {
		this.student = student;
	}
	

//	public Set getAdressgruppenverweises() {
//		return this.adressgruppenverweises;
//	}
//
//	public void setAdressgruppenverweises(Set adressgruppenverweises) {
//		this.adressgruppenverweises = adressgruppenverweises;
//	}
	

}
