package com.jrsii.entities;
// default package
// Generated Aug 11, 2014 10:36:41 AM by Hibernate Tools 3.4.0.CR1


import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQuery;

/**
 * Adressgruppenverweise generated by hbm2java
 */
@Entity
//@NamedQuery(name="Adressgruppenverweise.FindAllAdressgruppen_WHERE_agv.AdressgruppenID_EQUAL_ag.ID_AND_ag.Name_LIKE_adressgruppeName",
//            query="FROM Adressgruppenverweise agv ,Adressruppen ag WHERE ag.name LIKE :adressgruppeName ")
public class Adressgruppenverweise implements java.io.Serializable {

	@Id
	
	@GeneratedValue
	private int id;
	@ManyToOne
	@JoinColumn(name = "adressgruppenID")
	private Adressgruppen adressgruppen;
	@ManyToOne
	@JoinColumn(name = "adresseID")
	private Adressen adressen;

	public Adressgruppenverweise() {
	}

	public Adressgruppenverweise(int id) {
		this.id = id;
	}

	public Adressgruppenverweise(int id, Adressgruppen adressgruppen,
			Adressen adressen) {
		this.id = id;
		this.adressgruppen = adressgruppen;
		this.adressen = adressen;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Adressgruppen getAdressgruppen() {
		return this.adressgruppen;
	}

	public void setAdressgruppen(Adressgruppen adressgruppen) {
		this.adressgruppen = adressgruppen;
	}

	public Adressen getAdressen() {
		return this.adressen;
	}

	public void setAdressen(Adressen adressen) {
		this.adressen = adressen;
	}

}
