package com.jrsii.entities;
// default package
// Generated Aug 11, 2014 10:36:41 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

/**
 * Bankverbindungen generated by hbm2java
 */
@Entity
public class Bankverbindungen implements java.io.Serializable {

	@Id
	@GeneratedValue
	private int id;
	@ManyToOne
	@JoinColumn(name="adresseID")
	private Adressen adressen;
	private String name;
	private String inhaber;
	private String kontoNummer;
	private String blz;
	private String bic;
	private String swift;
	private Short typ;
	private Date letzteÄnderung;
	private Boolean gesperrt;

	public Bankverbindungen() {
	}

	public Bankverbindungen(int id) {
		this.id = id;
	}

	public Bankverbindungen(int id, Adressen adressen, String name,
			String inhaber, String kontoNummer, String blz, String bic,
			String swift, Short typ, Date letzteÄnderung, Boolean gesperrt) {
		this.id = id;
		this.adressen = adressen;
		this.name = name;
		this.inhaber = inhaber;
		this.kontoNummer = kontoNummer;
		this.blz = blz;
		this.bic = bic;
		this.swift = swift;
		this.typ = typ;
		this.letzteÄnderung = letzteÄnderung;
		this.gesperrt = gesperrt;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Adressen getAdressen() {
		return this.adressen;
	}

	public void setAdressen(Adressen adressen) {
		this.adressen = adressen;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getInhaber() {
		return this.inhaber;
	}

	public void setInhaber(String inhaber) {
		this.inhaber = inhaber;
	}

	public String getKontoNummer() {
		return this.kontoNummer;
	}

	public void setKontoNummer(String kontoNummer) {
		this.kontoNummer = kontoNummer;
	}

	public String getBlz() {
		return this.blz;
	}

	public void setBlz(String blz) {
		this.blz = blz;
	}

	public String getBic() {
		return this.bic;
	}

	public void setBic(String bic) {
		this.bic = bic;
	}

	public String getSwift() {
		return this.swift;
	}

	public void setSwift(String swift) {
		this.swift = swift;
	}

	public Short getTyp() {
		return this.typ;
	}

	public void setTyp(Short typ) {
		this.typ = typ;
	}

	public Date getLetzteÄnderung() {
		return this.letzteÄnderung;
	}

	public void setLetzteÄnderung(Date letzteÄnderung) {
		this.letzteÄnderung = letzteÄnderung;
	}

	public Boolean getGesperrt() {
		return this.gesperrt;
	}

	public void setGesperrt(Boolean gesperrt) {
		this.gesperrt = gesperrt;
	}

}
