package com.jrsii.entities;

// default package
// Generated Jan 31, 2014 3:40:33 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Verbindungen generated by hbm2java
 */
public class Verbindungen implements java.io.Serializable {

	private int id;
	private Adressen adressen;
	private String name;
	private String wert;
	private Short typ;
	private Date letzteÄnderung;
	private Boolean gesperrt;

	public Verbindungen() {
	}

	public Verbindungen(int id) {
		this.id = id;
	}

	public Verbindungen(int id, Adressen adressen, String name, String wert,
			Short typ, Date letzteÄnderung, Boolean gesperrt) {
		this.id = id;
		this.adressen = adressen;
		this.name = name;
		this.wert = wert;
		this.typ = typ;
		this.letzteÄnderung = letzteÄnderung;
		this.gesperrt = gesperrt;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Adressen getAdressen() {
		return this.adressen;
	}

	public void setAdressen(Adressen adressen) {
		this.adressen = adressen;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getWert() {
		return this.wert;
	}

	public void setWert(String wert) {
		this.wert = wert;
	}

	public Short getTyp() {
		return this.typ;
	}

	public void setTyp(Short typ) {
		this.typ = typ;
	}

	public Date getLetzteÄnderung() {
		return this.letzteÄnderung;
	}

	public void setLetzteÄnderung(Date letzteÄnderung) {
		this.letzteÄnderung = letzteÄnderung;
	}

	public Boolean getGesperrt() {
		return this.gesperrt;
	}

	public void setGesperrt(Boolean gesperrt) {
		this.gesperrt = gesperrt;
	}

}
